name: flutter_clip_shadow
description: A shadow cast by a clipped box. Support all BoxShadow class properties!
version: 1.0.0
homepage: https://github.com/lcsvcn/flutter-clip-shadow

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
